# Generated by Django 2.2 on 2020-08-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='plot',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='release',
            new_name='release_date',
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=45),
        ),
    ]
