# Generated by Django 2.2 on 2020-08-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uersername',
            new_name='username',
        ),
    ]
