# Generated by Django 2.2 on 2020-08-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_like_message_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='message_post',
            name='user_who_liked',
            field=models.ManyToManyField(related_name='liked_post', to='db_app.User'),
        ),
    ]
