# Generated by Django 2.2 on 2020-08-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_wall_message_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall_message',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
